config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 resources :articles
 root "articles#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates:title,presence:true
  validates:body,presence:true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :name,presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile,dependent: :destroy 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show,:edit,:update,:destroy]
  def index
    @articles = Article.order(created_at: :desc)
  end

  def show
  end

  def edit
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(artcle_params)
     if @article.save
      redirect_to @article,notice:'投稿に成功しました'
     else
      render :new,alert:'投稿に失敗しました'
     end
  end

  def update
    if @article.update(artcle_params)
      redirect_to @article,notice:'編集に成功しました'
    else
      render :edit,alert:'編集に失敗しました'
    end
  end

  def destroy
    if @article.destroy
      redirect_to root_path,notice:'削除に成功しました'
    else
      redirect_to root_path,alert:'削除に失敗しました'
    end
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def artcle_params
    params.require(:article).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%=form_for article do |f|%>
<%=f.label:title,"タイトル"%>
 <div class="form-group padding-top-15per">
<%=f.text_field:title ,class:'form-control'%>
</div>
<%=f.label:body,"本文"%>
 <div class="form-group padding-top-15per">
<%=f.text_area:body ,rows: 10,class:'form-control'%>
</div>
<%=f.submit class:'btn btn-success'%>
<%end%>

app/views/articles/edit.html.erb
<div class="container">
<div class="col-md-12 margin-top-5per artcle-block">
<h1 class="text-center">ブログの新規作成</h1>
<%=image_tag 'tree.jpg', class:'img-responsive padding-top-15per article-image'%>
<div class="padding-bottom-15">
<%=render 'form',article:@article%>
</div>
</div>
</div>

app/views/articles/index.html.erb
<div class="container">

<div class="row">
<% @articles.each do |article|%>
<%= link_to article do%>
<div class="col-md-4 margin-top-5per artcle-block">
<%=image_tag 'tree.jpg', class:'img-responsive padding-top-15per'%>
<div class="padding-bottom-15">
<p class="title">
<%=article.title%>
</p>
<p>
<%=article.created_at.strftime("%Y年%m月%d日")%>
</p>
</div>
</div>
<%end%>
<%end%>
</div>
<div class="row">
<%=link_to '新規作成',new_article_path,class:"margin-top-5per btn btn-primary",style:'margin-bottom:10px;'%>
</div>
</div>

app/views/articles/new.html.erb
<div class="container">
<div class="col-md-12 margin-top-5per artcle-block">
<h1 class="text-center">ブログの新規作成</h1>
<%=image_tag 'tree.jpg', class:'img-responsive padding-top-15per article-image'%>
<div class="padding-bottom-15">
<%=render 'form',article:@article%>
</div>
</div>
</div>

app/views/articles/show.html.erb
<div class="container">
<div class="col-md-12 margin-top-5per artcle-block">
<%=image_tag 'tree.jpg', class:'img-responsive padding-top-15per article-image'%>
<h1><%= @article.title%></h1>
<div class="padding-bottom-15">
<p class="title">
<%=@article.body%>
</p>
<p class="text-right">
<%=@article.created_at.strftime("%Y年%m月%d日")%>
</p>
</div>
<%=link_to '編集',edit_article_path(@article),class:'btn btn-primary',style:'margin-bottom:10px;margin-right:10px;'%>
<%=link_to '削除',article_path(@article),method: :delete,data: {confirm: "削除しますか？"},class:'btn btn-danger',style:'margin-bottom:10px;'%>
</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if user_signed_in? %>
          <a class="navbar-brand" href="/">Blog</a>
          <%else%>
          <a class="navbar-brand" href="/">ブログサービス</a>
          <%end%>
          
        </div>
        <div class="collapse navbar-collapse" id="navigation">
          <p class="navbar-text navbar-right">
          <% if user_signed_in? %>
          <%=link_to '新規作成',new_article_path%>
          &nbsp;
          <%=link_to 'ログアウト',destroy_user_session_path, method: :delete %>
          <%else%>
          <%=link_to 'ユーザー登録',new_user_registration_path%>
          &nbsp;
          <%=link_to 'ログイン',new_user_session_path%>
          <%end%>
          </p>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  

    <%= render 'layouts/header'%>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>